#!/usr/bin/env python

import argparse
from datetime import datetime
import numpy as np

from lighthouse.execution.runner import Runner
from lighthouse.pipeline.driver import CompilerDriver
from lighthouse import dialects as lh_dialects


def _get_input_type(input_type_str: str):
    if input_type_str == "f16":
        return np.float16
    elif input_type_str == "bf16":
        return np.bfloat16
    elif input_type_str == "f32":
        return np.float32
    elif input_type_str == "f64":
        return np.float64

    elif input_type_str == "i8":
        return np.int8
    elif input_type_str == "i16":
        return np.int16
    elif input_type_str == "i32":
        return np.int32
    elif input_type_str == "i64":
        return np.int64
    else:
        raise ValueError(f"Unsupported input type: {input_type_str}")


def add_lower_to_llvm_stages() -> list[str]:
    """
    Adds the LLVM lowering passes to guarantee the IR can be ingested by the ExecutionEngine.
    """
    stages = [
        "convert-linalg-to-loops",
        "fold-memref-alias-ops",
        "expand-strided-metadata",
        "canonicalize",
        "convert-vector-to-scf",
        "lower-affine",
        "convert-scf-to-cf",
        "convert-vector-to-llvm",
        "convert-to-llvm",
        "reconcile-unrealized-casts",
    ]
    return stages


if __name__ == "__main__":
    Parser = argparse.ArgumentParser(
        description="""
    Lighthouse Optimization Runner: Optionally applies a series of transformations to an input MLIR module,
    and executes it on a device.
    """
    )
    Parser.add_argument(
        "payload_module", type=str, help="Path to the payload MLIR module to optimize."
    )
    Parser.add_argument(
        "--entry-point",
        type=str,
        required=True,
        help="Name of the entrypoint function in the payload MLIR module.",
    )
    Parser.add_argument(
        "--input-shape",
        action="append",
        required=True,
        help="Shape of the input tensors in format M,N;N,K;...",
    )
    Parser.add_argument(
        "--input-type",
        required=True,
        help="Type of the input tensor for the entrypoint function.",
    )
    Parser.add_argument(
        "--seed",
        type=int,
        default=0,
        help="Random seed for initializing input tensors.",
    )
    Parser.add_argument(
        "--stage",
        action="append",
        required=True,
        help="List of transformations to apply to the input module.",
    )
    Parser.add_argument(
        "-O",
        type=int,
        default=3,
        help="Optimization level. Default is 3.",
    )
    Parser.add_argument(
        "--benchmark",
        action=argparse.BooleanOptionalAction,
        help="Whether to run the benchmark. Default is False.",
    )
    Parser.add_argument(
        "--print-optimized-module",
        action=argparse.BooleanOptionalAction,
        help="Whether to print the optimized module. Default is False.",
    )
    Parser.add_argument(
        "--print-tensor",
        type=int,
        default=0,
        help="Print the Nth tensor. Default is 0 (no print).",
    )
    Parser.add_argument(
        "--print-mlir-after-all",
        action=argparse.BooleanOptionalAction,
        help="Whether to print the MLIR module after all stages. Default is False.",
    )
    args = Parser.parse_args()

    # Initialize the random seed, for stable tests
    if args.seed:
        np.random.seed(args.seed)
    else:
        np.random.seed(int(datetime.now().timestamp()))

    # Create the driver and run the pipeline.
    # Empty args means no stages will be run and the module will be imported as-is.
    driver = CompilerDriver(args.payload_module)

    if args.benchmark:
        # Calling the benchmark wrapper, not the entry point.
        # FIXME: Eliminate this cross-dependency between the Runner and the Driver.
        with driver.context:
            lh_dialects.register_and_load()
            bench_wrapper = Runner.get_bench_wrapper_schedule(args.entry_point)
            driver.add_module_stage(bench_wrapper)
    else:
        # Calling the entry point directly, so set the attribute on the entry point function.
        driver.make_function_callable(args.entry_point)

    # Add the remaining stages defined by the user.
    driver.add_stages(args.stage)

    # Add the necessary LLVM lowering stages to ensure the module can be executed by the ExecutionEngine.
    driver.add_stages(add_lower_to_llvm_stages())

    # Run the pipeline to get the optimized module.
    optimized_module = driver.run(print_after_all=args.print_mlir_after_all)
    if args.print_optimized_module:
        print(optimized_module)

    # Initialize the device data
    # TODO: Allow automatic inspection of the payload module if the user doesn't provide input shapes.
    buffers = []
    for shape in args.input_shape:
        for sub_shape in shape.split(","):
            shape = tuple(map(int, sub_shape.split("x")))
            buffers.append(
                np.random.rand(*shape).astype(_get_input_type(args.input_type))
            )

    # Create the runner and execute/benchmark the module.
    runner = Runner(optimized_module, opt_level=args.O)
    if args.benchmark:
        time_array = runner.benchmark(host_input_buffers=buffers)
        print(f"{len(time_array)} runs: {np.mean(time_array)} seconds")
    else:
        runner.execute(
            payload_function_name=args.entry_point,
            host_input_buffers=buffers,
        )

    # Optionally print the output tensor after execution.
    if args.print_tensor > 0:
        idx = args.print_tensor - 1
        print(f"Output: {buffers[idx]}")
